[book]
title = "RPG Power Forge"
authors = ["Gif", "Chiw", "Noiracide"]
description = "The Unity package to create RPG with ease"
language = "en"
src = "."

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"

[output.html.print]
enable = false    # include support for printable output
page-break = true # insert page-break after each chapter